---
- hosts: all
  vars:
    - container_registry: "container-registry.oracle.com"
    - container_registry_username: ""
    - container_registry_password: ""
    - autonmous_database_tag: ""
    - weblogic_server_tag: ""
  tasks:
    - name: Login to  and create containers/auth.json
      containers.podman.podman_login:
        username: "{{ container_registry_username }}"
        password: "{{ container_registry_password }}"
        registry: "{{ container_registry }}"

    - name: Clone a repo with separate git directory
      ansible.builtin.git:
        repo: https://github.com/qupwork/oracle
        dest: /tmp

    - name: Build a autonomous database image
      shell: "./tmp/oracle/autonomous-database/build.sh $CUSTOM_IMAGE_TAG"
      environment:
        CUSTOM_IMAGE_TAG: "oracle/oad:{{ autonomous_database_tag }}"

    - name: Build a weblogic server image
      shell: "./tmp/oracle/weblogic-server/build.sh"
      environment:
        CUSTOM_IMAGE_TAG: "oracle/weblogic:{{ weblogic_server_tag }}"
