---
- hosts: all
  vars:
    - container_registry: "container-registry.oracle.com"
    - container_registry_username: ""
#    - container_registry_password: ""
    - autonomous_database_tag: ""
    - weblogic_server_tag: ""
  vars_prompt:
    - name: container_registry_password
      prompt: Enter the registry password
  tasks:
    - name: Login to  and create containers/auth.json
      containers.podman.podman_login:
        username: "{{ container_registry_username }}"
        password: "{{ container_registry_password }}"
        registry: "{{ container_registry }}"
      become: true

    - name: Recursively remove directory
      ansible.builtin.file:
        path: /tmp/oracle
        state: absent

    - name: Clone a repo with separate git directory
      ansible.builtin.git:
        repo: https://github.com/oracleweboadb/oracle
        dest: /tmp/oracle
        version: main
        force: yes

    - name: Build a autonomous database image
      ansible.builtin.shell: |
        export CUSTOM_IMAGE_TAG="oracle/oad:{{ autonomous_database_tag }}"
        
        chmod +x /tmp/oracle/autonomous-database/build.sh
        /tmp/oracle/autonomous-database/build.sh $CUSTOM_IMAGE_TAG
      args:
        executable: /bin/bash
      become: true

    - name: Build a weblogic server image
      ansible.builtin.shell: |
        export CUSTOM_IMAGE_TAG="oracle/weblogic:{{ weblogic_server_tag }}"
        export WEBLOGIC_USERNAME={{ weblogic_username }}
        export WEBLOGIC_PASSWORD={{ weblogic_password }}
        export PROPERTIES_PATH=/tmp/oracle/weblogic-server/properties/docker-build/domain_security.properties
        
        envsubst < $PROPERTIES_PATH | tee $PROPERTIES_PATH
                
        chmod +x /tmp/oracle/weblogic-server/build.sh
        /tmp/oracle/weblogic-server/build.sh
      args:
        executable: /bin/bash
      become: true
