---
- hosts: all
  vars:
    - container_registry: "localhost/"
    - autonomous_database_tag: ""
    - weblogic_server_tag: ""
    - autonomous_database_wallet_password: "123456789aA123"
    - autonomous_admin_password: "123456789aA123"
    - weblogic_username: "hello"
    - weblogic_password: "123456789"
    - security_properties: |-
        username={{ weblogic_username }}
        password={{ weblogic_password }}
        JAVA_OPTIONS=-Dweblogic.StdoutDebugEnabled=true
  tasks:
    - name: Create a oadb volume
      containers.podman.podman_volume:
        state: present
        name: oadb_volume
        label:
          owner: autonomous-database
        options:
          - "type=ext4"

    - name: "Create the autonomous database container"
      containers.podman.podman_container:
        name: oadb
        hostname: oadb
        image: "{{ container_registry }}oracle/oad:{{ autonomous_database_tag }}"
        publish:
        - 1521:1522
        - 1522:1522
        - 8443:8443
        - 27017:27017
        env:
          WORKLOAD_TYPE: ATP
          WALLET_PASSWORD: "{{ autonomous_database_wallet_password }}"
          ADMIN_PASSWORD: "{{ autonomous_admin_password }}"
        cap_add:
          - SYS_ADMIN
        device:
          - /dev/fuse
        volume:
          - "oadb_volume:/u01/data"
        state: started
        recreate: true
        generate_systemd:
          names: true
          restart_policy: always
      become: true

    - name: Ensure the directory /example/directory exists
      ansible.builtin.file:
        path: /tmp/properties
        state: directory
        mode: '0755'

    - name: Creating a file with content
      copy:
        dest: "/tmp/properties/security.properties"
        content: "{{ security_properties }}"

    - name: "Create the admin weblogic server container"
      containers.podman.podman_container:
        name: weblogic-admin
        hostname: weblogic-admin
        image: "{{ container_registry }}oracle/weblogic:{{ weblogic_server_tag }}"
        publish:
        - 7001:7001
        volume:
          - "/tmp/properties:/u01/oracle/properties:Z"
        state: started
        recreate: true
        generate_systemd:
          names: true
          restart_policy: always
      become: true

    - name: "Create the admin weblogic server container"
      containers.podman.podman_container:
        name: managed-server-1
        hostname: managed-server-1
        image: "{{ container_registry }}oracle/weblogic:{{ weblogic_server_tag }}"
        publish:
          - 8001:8001
        volume:
          - "/tmp/properties:/u01/oracle/properties:Z"
        state: started
        recreate: true
        command: "startManagedServer.sh"
        generate_systemd:
          names: true
          restart_policy: always
      become: true
