---
- hosts: all
  vars:
    - container_registry: "container-registry.oracle.com"
    - container_registry_username: ""
    - container_registry_password: ""
    - container_registry_local: "localhost/"
    - autonomous_database_tag: ""
    - weblogic_server_tag: ""
    - autonomous_database_wallet_password: "123456789aA123"
    - autonomous_admin_password: "123456789aA123"
    - weblogic_username: "hello"
    - weblogic_password: "123456789"
    - github_username: ""
    - github_password: ""
  tasks:
    - name: Clone a repo with separate git directory
      ansible.builtin.git:
        repo: https://github.com/oracleweboadb/oracle
        dest: /home/root/oracle
        version: main
        force: yes
      become: true

    - name: ensure python3 is installed
      become: yes
      ansible.builtin.package:
        name:
          - python3
          - python3-pip
        state: present

    - name: Build a autonomous database image
      ansible.builtin.shell: |
        pip3 install --include-deps ansible
        pip3 install ansible-core
        ansible-playbook /home/root/oracle/ansible-main/build_and_deploy.yaml \
        --extra-vars "container_registry={{ container_registry }} container_registry_username={{ container_registry_username }} container_registry_password={{ container_registry_password }} container_registry_local={{ container_registry_local }} autonomous_database_tag={{ autonomous_database_tag }} weblogic_server_tag={{ weblogic_server_tag }} autonomous_database_wallet_password={{ autonomous_database_wallet_password }} autonomous_admin_password={{ autonomous_admin_password }} weblogic_username={{ weblogic_username }} weblogic_password={{ weblogic_password }}"
      args:
        executable: /bin/bash
      become: true


